require "../spec_helper"

private def convention(path : String, frontmatter : String) : AgentApropos::Convention
  AgentApropos::Convention.parse(path, "---\n#{frontmatter}\n---\nbody\n")
end

describe AgentApropos::Skills do
  describe ".slug_for" do
    it "is the filename without its .md extension" do
      AgentApropos::Skills.slug_for("docs/conventions/workflows/ship-a-feature.md")
        .should eq("ship-a-feature")
    end
  end

  describe ".wrappers" do
    it "renders name + verbatim description with a banner and a source pointer" do
      conventions = [convention("docs/conventions/workflows/foo.md",
        %(skill: true\ndescription: "Use when foo"))]

      wrappers = AgentApropos::Skills.wrappers(conventions)
      wrappers.keys.should eq(["foo"])
      wrappers["foo"].should eq(<<-SKILL + "\n")
        ---
        name: foo
        description: Use when foo
        ---

        <!-- GENERATED by `apropos generate` — do not edit. Edit the source doc instead. -->

        Read `docs/conventions/workflows/foo.md` and follow it.
        SKILL
    end

    it "inlines the doc body instead of a pointer when the source lives outside the repo" do
      conventions = [convention("../shared-conventions/workflows/foo.md",
        %(skill: true\ndescription: "Use when foo"))]

      wrapper = AgentApropos::Skills.wrappers(conventions)["foo"]
      wrapper.should_not contain("Read `")
      wrapper.should contain("body")
    end

    it "inlines the body's exact bytes, not stripped, when the source lives outside the repo" do
      text = "---\nskill: true\ndescription: \"Use when foo\"\n---\n# Foo\n\ncontent line   \n\n\n"
      body = AgentApropos::Frontmatter.split(text)[1]
      conventions = [AgentApropos::Convention.parse("../shared-conventions/workflows/foo.md", text)]

      wrapper = AgentApropos::Skills.wrappers(conventions)["foo"]
      wrapper.should end_with(body)
    end

    it "appends a trailing newline when inlining a body that lacks one" do
      text = "---\nskill: true\ndescription: \"Use when foo\"\n---\nno trailing newline"
      conventions = [AgentApropos::Convention.parse("../shared-conventions/workflows/foo.md", text)]

      wrapper = AgentApropos::Skills.wrappers(conventions)["foo"]
      wrapper.should end_with("no trailing newline\n")
    end

    it "ignores docs without skill: true" do
      conventions = [
        convention("docs/conventions/a.md", %(paths: ["src/**"])),
        convention("docs/conventions/b.md", %(contents: ['\\bx\\b'])),
      ]
      AgentApropos::Skills.wrappers(conventions).should be_empty
    end

    it "quotes a description that needs YAML escaping, byte-stably" do
      conventions = [convention("docs/conventions/workflows/q.md",
        %(skill: true\ndescription: "Use when: a \\"quoted\\" case"))]
      wrapper = AgentApropos::Skills.wrappers(conventions)["q"]
      wrapper.should contain(%(description: 'Use when: a "quoted" case'))
    end

    it "raises on a slug collision across directories" do
      conventions = [
        convention("docs/conventions/workflows/dup.md", %(skill: true\ndescription: "Use when A")),
        convention("docs/conventions/other/dup.md", %(skill: true\ndescription: "Use when B")),
      ]
      expect_raises(AgentApropos::Skills::Error, /slug collision on 'dup'/) do
        AgentApropos::Skills.wrappers(conventions)
      end
    end

    it "raises when a skill doc has no description" do
      conventions = [convention("docs/conventions/workflows/n.md", %(skill: true))]
      expect_raises(AgentApropos::Skills::Error, /no `description`/) do
        AgentApropos::Skills.wrappers(conventions)
      end
    end
  end
end
