require "./agent"

module AgentApropos
  module Agents
    # OpenCode: a generated Bun plugin that bridges `agent-apropos hook pre`
    # into `tool.execute.before` (Layer 2) and `agent-apropos hook post` into
    # `tool.execute.after` (Layer 3).
    class OpenCode < Agent
      PLUGIN_RELATIVE = Path[".opencode", "plugins", "agent-apropos.js"]

      def name : String
        "opencode"
      end

      # Write (or update) the OpenCode Bun plugin. Uses `Init.sync` so a
      # re-run is a no-op when the content is identical.
      def scaffold(repo_root : Path, fs : Filesystem, options : Init::Options, stdout : IO) : Nil
        path = repo_root.join(PLUGIN_RELATIVE).to_s
        existing = fs.read?(path)
        Init.sync(fs, options, stdout, path, PLUGIN_JS, existing, ".opencode/plugins/agent-apropos.js")
      end

      # Check for the OpenCode binary and the generated plugin. Advisory
      # only: never fails, so a Claude-only repo is not penalised.
      def checks(repo_root : Path, fs : Filesystem, env : Environment) : Array(Check)
        [plugin_check(repo_root, fs, env)]
      end

      private def plugin_check(repo_root : Path, fs : Filesystem, env : Environment) : Check
        unless env.which("opencode")
          return Check.new(:ok, "opencode", "not on PATH; skipped plugin check")
        end
        plugin = repo_root.join(PLUGIN_RELATIVE).to_s
        if fs.exists?(plugin)
          Check.new(:ok, "opencode", "plugin wired")
        else
          Check.new(:warn, "opencode", "plugin absent; run `agent-apropos init --tool opencode`")
        end
      end

      # Injects convention context using `client.session.prompt` with
      # `noReply: true`, which adds a message to the conversation without
      # triggering a new AI turn. This is the documented OpenCode API for
      # injecting context from plugins.
      #
      # Layer 2 (path-scoped) fires via `tool.execute.before` — on both a
      # write and a read (Layer 2 depends only on the target path, which a
      # read carries exactly like an edit, so the rule can land on the
      # model's first read instead of only once it writes there). Layer 3
      # (construct-scoped) fires via `tool.execute.after` using the written
      # content for regex matching — read-only, since it needs content that
      # doesn't exist yet on a mere read.
      #
      # Both hooks fail open: any error exits silently and never blocks an
      # edit. The session ID is read from `input.sessionID` when available
      # and tracked through session events as a fallback.
      PLUGIN_JS = <<-JS
        // Generated by `agent-apropos init --tool opencode` — do not edit. Re-run to regenerate.
        //
        // Bridges agent-apropos's hook system into OpenCode using client.session.prompt
        // with noReply:true, which injects convention context into the conversation
        // without triggering an AI response.
        //
        // Layer 2 (path-scoped)    — fires via tool.execute.before (reads and pre-write).
        // Layer 3 (construct-scoped) — fires via tool.execute.after  (post-write).
        // Both fail open: any error produces no output and never blocks an edit.
        // See docs/conventions/README.md for the layer model.

        export const AgentAproposPlugin = async ({ worktree, client }) => {
          // Session ID tracked through events; also read from input.sessionID when
          // the plugin event exposes it (undocumented but likely present).
          let sessionID = null

          async function callHook(sub, payload) {
            try {
              const proc = Bun.spawn(["agent-apropos", "hook", sub], {
                stdin: new Blob([JSON.stringify(payload)]),
                stdout: "pipe",
                cwd: worktree,
              })
              const text = await new Response(proc.stdout).text()
              const parsed = JSON.parse(text.trim())
              return parsed?.hookSpecificOutput?.additionalContext ?? ""
            } catch {
              return ""
            }
          }

          async function inject(sid, ctx) {
            if (!ctx || !sid) return
            try {
              await client.session.prompt({
                path: { id: sid },
                body: { noReply: true, parts: [{ type: "text", text: ctx }] },
              })
            } catch {
              // Fail open
            }
          }

          function makePayload(input, args, withContent) {
            return {
              session_id: input.sessionID ?? sessionID,
              cwd: worktree,
              tool_name: input.tool,
              tool_input: {
                file_path: args?.filePath,
                ...(withContent ? {
                  content:    args?.content,
                  new_string: args?.newString,
                } : {}),
              },
            }
          }

          return {
            // Track session ID so inject() can call client.session.prompt.
            event: async ({ event }) => {
              const id = event.properties?.session?.id ?? event.properties?.id
              if (id && (event.type === "session.created" || event.type === "session.updated")) {
                sessionID = id
              }
            },

            // Layer 2 — path-scoped: inject BEFORE the write so the model sees
            // the rule while still in the current tool-processing turn. Also
            // fires on "read" — Layer 2 depends only on the target path, which
            // a read carries exactly like an edit, so the rule can land as
            // early as the model's first read instead of only once it writes
            // there. OpenCode delivers the tool arguments in the SECOND
            // callback parameter (output.args) for tool.execute.before; older
            // builds put them on input.args. Read output first, fall back to
            // input.
            "tool.execute.before": async (input, output) => {
              if (!["edit", "write", "apply_patch", "read"].includes(input.tool)) return
              const args = output?.args ?? input.args
              if (!args?.filePath) return
              const ctx = await callHook("pre", makePayload(input, args, false))
              await inject(input.sessionID ?? sessionID, ctx)
            },

            // Layer 3 — construct-scoped: inject AFTER the write using the written
            // content for regex matching. Here OpenCode carries args on input;
            // the same output-first fallback keeps this robust across versions.
            "tool.execute.after": async (input, output) => {
              if (!["edit", "write", "apply_patch"].includes(input.tool)) return
              const args = output?.args ?? input.args
              if (!args?.filePath) return
              const ctx = await callHook("post", makePayload(input, args, true))
              await inject(input.sessionID ?? sessionID, ctx)
            },
          }
        }
        JS
    end
  end
end
