require "../spec_helper"

private def convention(path : String, frontmatter : String) : Muninn::Convention
  Muninn::Convention.parse(path, "---\n#{frontmatter}\n---\nbody\n")
end

describe Muninn::Skills do
  describe ".slug_for" do
    it "is the filename without its .md extension" do
      Muninn::Skills.slug_for("docs/conventions/workflows/ship-a-feature.md")
        .should eq("ship-a-feature")
    end
  end

  describe ".wrappers" do
    it "renders name + verbatim description with a banner and a source pointer" do
      conventions = [convention("docs/conventions/workflows/foo.md",
        %(skill: true\ndescription: "Use when foo"))]

      wrappers = Muninn::Skills.wrappers(conventions)
      wrappers.keys.should eq(["foo"])
      wrappers["foo"].should eq(<<-SKILL + "\n")
        ---
        name: foo
        description: Use when foo
        ---

        <!-- GENERATED by `muninn generate` — do not edit. Edit the source doc instead. -->

        Read `docs/conventions/workflows/foo.md` and follow it.
        SKILL
    end

    it "ignores docs without skill: true" do
      conventions = [
        convention("docs/conventions/a.md", %(paths: ["src/**"])),
        convention("docs/conventions/b.md", %(contents: ['\\bx\\b'])),
      ]
      Muninn::Skills.wrappers(conventions).should be_empty
    end

    it "quotes a description that needs YAML escaping, byte-stably" do
      conventions = [convention("docs/conventions/workflows/q.md",
        %(skill: true\ndescription: "Use when: a \\"quoted\\" case"))]
      wrapper = Muninn::Skills.wrappers(conventions)["q"]
      wrapper.should contain(%(description: 'Use when: a "quoted" case'))
    end

    it "raises on a slug collision across directories" do
      conventions = [
        convention("docs/conventions/workflows/dup.md", %(skill: true\ndescription: "Use when A")),
        convention("docs/conventions/other/dup.md", %(skill: true\ndescription: "Use when B")),
      ]
      expect_raises(Muninn::Skills::Error, /slug collision on 'dup'/) do
        Muninn::Skills.wrappers(conventions)
      end
    end

    it "raises when a skill doc has no description" do
      conventions = [convention("docs/conventions/workflows/n.md", %(skill: true))]
      expect_raises(Muninn::Skills::Error, /no `description`/) do
        Muninn::Skills.wrappers(conventions)
      end
    end
  end
end
