require "../spec_helper"
require "file_utils"

# End-to-end `generate` against the built binary in a throwaway fixture repo,
# byte-comparing the emitted wrapper to a golden and asserting the `--check`
# drift gate flips on a hand-edit. Complements the unit specs, which drive the
# same logic through an injected filesystem.
describe "apropos generate (binary)" do
  binary = File.join(Dir.tempdir, "apropos-gen-#{Process.pid}")

  Spec.before_suite do
    status = Process.run(
      "crystal",
      ["build", "src/apropos.cr", "-o", binary],
      output: Process::Redirect::Inherit,
      error: Process::Redirect::Inherit
    )
    raise "failed to build apropos binary for integration specs" unless status.success?
  end

  Spec.after_suite do
    File.delete?(binary)
  end

  it "emits a byte-stable skill wrapper and enforces the --check gate" do
    dir = File.tempname("apropos-gen-repo")
    begin
      Dir.mkdir_p(File.join(dir, "docs/conventions/workflows"))
      File.write(File.join(dir, "docs/conventions/workflows/ship.md"),
        "---\nskill: true\ndescription: \"Use when shipping a feature\"\n---\n\n# Shipping\n\nbody\n")

      run = Process.run(binary, ["generate", "--repo-root", dir], output: IO::Memory.new)
      run.exit_code.should eq(0)

      golden = <<-SKILL + "\n"
        ---
        name: ship
        description: Use when shipping a feature
        ---

        <!-- GENERATED by `apropos generate` — do not edit. Edit the source doc instead. -->

        Read `docs/conventions/workflows/ship.md` and follow it.
        SKILL
      File.read(File.join(dir, ".claude/skills/ship/SKILL.md")).should eq(golden)
      File.read(File.join(dir, ".gemini/skills/ship/SKILL.md")).should eq(golden)

      clean = Process.run(binary, ["generate", "--check", "--repo-root", dir], output: IO::Memory.new)
      clean.exit_code.should eq(0)

      File.write(File.join(dir, ".claude/skills/ship/SKILL.md"), "tampered\n")
      dirty = Process.run(binary, ["generate", "--check", "--repo-root", dir], output: IO::Memory.new)
      dirty.exit_code.should eq(1)
    ensure
      FileUtils.rm_rf(dir)
    end
  end
end
