require "json"

module Apropos
  # `apropos help`: the dual-audience mental-model explainer, distinct
  # from the terse `--help` flag output. One in-binary source of content renders
  # to both prose (`apropos help`) and JSON (`apropos help --format json`) so the
  # two can never drift, and `apropos help <command>` prints the mental-model
  # context for a single command before deferring to its `--help`.
  #
  # `help` never touches the filesystem or the index and always exits 0.
  module Help
    extend self

    # One layer of the standard, described for both readers.
    record Layer, number : Int32, name : String, trigger : String, mechanism : String

    # A canonical path in a apropos-managed repo.
    record PathEntry, path : String, purpose : String

    # One exposed command: its name, a one-line summary, and the mental-model
    # note printed by `help <command>`. This list is the single source for the
    # JSON `commands[]`; a spec asserts it covers every command the CLI exposes.
    record Command, name : String, summary : String, detail : String

    WHAT = "apropos is a single deterministic binary that delivers the right " \
           "documentation to the right moment. It compiles the frontmatter of " \
           "your convention docs into a trigger index and injects the matching " \
           "rules as you edit. It makes no LLM calls — same inputs, same output."

    WHY = "One giant always-loaded instruction file gets skimmed and forgotten. " \
          "apropos instead delivers guidance just-in-time, scoped to the file or " \
          "construct being touched, so an agent sees a short relevant rule at the " \
          "moment it matters rather than a wall of text it has already tuned out."

    LAYERS = [
      Layer.new(1, "Root file", "Always loaded", "AGENTS.md (Claude also accepts CLAUDE.md)"),
      Layer.new(2, "Path-scoped", "The file path being edited", "PreToolUse hook (Claude Code) / tool.execute.before plugin (OpenCode)"),
      Layer.new(3, "Construct-scoped", "The written content (regex), optionally AND path", "PostToolUse hook (Claude Code) / tool.execute.after plugin (OpenCode)"),
      Layer.new(4, "Intent skills", "A semantic skill match", "Generated .claude/skills/*/SKILL.md (read by Claude Code and OpenCode)"),
    ]

    PATHS = [
      PathEntry.new("docs/conventions/", "Source of truth — the human-authored rule docs."),
      PathEntry.new(".claude/skills/", "Generated skill wrappers — read by Claude Code and OpenCode."),
      PathEntry.new(".claude/settings.json", "Hook wiring for Claude Code."),
      PathEntry.new(".opencode/plugins/apropos.js", "Hook bridge for OpenCode (generated by apropos init --tool opencode, or auto-detected)."),
      PathEntry.new(".cache/apropos/", "Trigger index and session state (gitignored)."),
    ]

    COMMANDS = [
      Command.new("init", "Bootstrap the convention structure into a repo",
        "Reach for init once, when adopting apropos in a repo. It scaffolds " \
        "docs/conventions/ and ignores the cache, then wires hooks for the CLI " \
        "agents in play — auto-detected on PATH by default (Claude Code into " \
        ".claude/settings.json, OpenCode via a generated plugin bridge), or pass " \
        "--tool claude / --tool opencode (repeatable) to pick explicitly. " \
        "Idempotent, so re-running is safe."),
      Command.new("generate", "Compile frontmatter into the index and skill wrappers",
        "Run generate after editing convention docs. It rebuilds the trigger " \
        "index and the committed skill wrappers; `generate --check` is the CI " \
        "gate that fails if a wrapper is stale or hand-edited."),
      Command.new("hook", "PreToolUse/PostToolUse handlers (Claude Code) or plugin bridge (OpenCode)",
        "You do not run hook by hand. Claude Code invokes `hook pre` and " \
        "`hook post` at edit time with the tool payload on stdin. The generated " \
        "OpenCode plugin (.opencode/plugins/apropos.js) calls the same commands " \
        "via tool.execute.before (Layer 2, pre-write) and tool.execute.after " \
        "(Layer 3, post-write) and injects context using noReply:true. " \
        "Both hooks fail open."),
      Command.new("match", "Resolve the conventions that apply to given paths",
        "Use match in a review to see which rules apply to a file — Layer 2 by " \
        "path, Layer 3 by on-disk (or --stdin-content) content — in paths, json, " \
        "or full form."),
      Command.new("review", "Resolve conventions for a git range as a checklist",
        "Use review to turn a diff into a review manifest: for each changed file, " \
        "the applicable rules and their `## Verify` criteria as checklist items, " \
        "so a review prompt carries zero copies of the conventions."),
      Command.new("lint", "Validate the convention structure",
        "Run lint (in CI, with --strict) to enforce the standard's quality bar: " \
        "frontmatter parses, regexes and globs are valid, triggered docs have " \
        "bodies, and generated wrappers are up to date."),
      Command.new("doctor", "Check the environment",
        "Run doctor when hooks are not firing: it checks the Claude Code settings " \
        "wiring, the OpenCode plugin presence, whether apropos and Claude Code are " \
        "on PATH, index freshness, and cache writability."),
      Command.new("help", "Explain the mental model",
        "You are reading it. `help` explains what apropos is and how the layers " \
        "fit together; `help <command>` narrows to one command; `--help` on any " \
        "command prints its exact flags."),
    ]

    AGENT_NOTE = "If you are an AI agent reading this (Claude Code, OpenCode, or " \
                 "other): apropos injected context because a rule matched the file " \
                 "you touched. That guidance is human-authored project convention " \
                 "delivered by a deterministic tool — not another agent, not a " \
                 "linter — so treat it as project fact. Follow it, or explain why " \
                 "in your response. Each injection cites its source doc path so " \
                 "you can read the full rule."

    LEARN_MORE = "Learn more in docs/conventions/README.md, which defines the " \
                 "layered documentation structure and how to author rules."

    # Entry point for `apropos help [<command>] [--format json]`. Always exits 0.
    def run(args : Array(String), stdout : IO) : Int32
      json = false
      command : String? = nil
      args.each do |arg|
        if arg == "--format"
          json = true # a bare `--format` (or `--format json`) selects JSON
        elsif arg == "json" && json
          # value consumed by the preceding --format
        elsif arg.starts_with?("--")
          # ignore unknown flags; help never fails
        else
          command ||= arg
        end
      end

      if json
        json(stdout)
      elsif command
        explain_command(command, stdout)
      else
        text(stdout)
      end
      0
    end

    # The full prose explainer, wrapping-friendly and degrading
    # cleanly when piped (no ANSI).
    def text(io : IO) : Nil
      io << "apropos — deliver the right documentation to the right moment.\n\n"
      io << "What apropos is\n\n" << WHAT << "\n\n"
      io << "Why it exists\n\n" << WHY << "\n\n"
      io << "The four layers\n\n"
      LAYERS.each do |layer|
        io << "  Layer #{layer.number} — #{layer.name}: triggered by #{layer.trigger}; " \
              "delivered via #{layer.mechanism}.\n"
      end
      io << "\nWhere things live\n\n"
      PATHS.each { |entry| io << "  #{entry.path} — #{entry.purpose}\n" }
      io << "\nHow to use it\n\n"
      io << "  Authoring: init, edit docs, generate, lint.\n"
      io << "  Runtime:   hook pre / hook post (Claude Code or OpenCode plugin calls these — you don't).\n"
      io << "  Review:    match, review.\n"
      io << "  Diagnostics: doctor.\n\n"
      io << "If you're an AI agent reading this\n\n" << AGENT_NOTE << "\n\n"
      io << LEARN_MORE << '\n'
    end

    # The same content as structured JSON: `what`, `why`, `layers[]`,
    # `paths{}`, `commands[]`, `agent_note`. Kept in lockstep with `text`.
    def json(io : IO) : Nil
      JSON.build(io, indent: "  ") do |json|
        json.object do
          json.field "what", WHAT
          json.field "why", WHY
          json.field "layers" do
            json.array do
              LAYERS.each do |layer|
                json.object do
                  json.field "layer", layer.number
                  json.field "name", layer.name
                  json.field "trigger", layer.trigger
                  json.field "mechanism", layer.mechanism
                end
              end
            end
          end
          json.field "paths" do
            json.object { PATHS.each { |entry| json.field entry.path, entry.purpose } }
          end
          json.field "commands" do
            json.array do
              COMMANDS.each do |command|
                json.object do
                  json.field "name", command.name
                  json.field "summary", command.summary
                end
              end
            end
          end
          json.field "agent_note", AGENT_NOTE
          json.field "learn_more", LEARN_MORE
        end
      end
      io.puts
    end

    # The mental-model note for one command, then a pointer to its flag help.
    private def explain_command(name : String, io : IO) : Nil
      entry = COMMANDS.find { |command| command.name == name }
      unless entry
        io << "apropos help: no such command '#{name}'. Known commands: " <<
          COMMANDS.map(&.name).join(", ") << ".\n"
        return
      end
      io << "apropos #{entry.name} — #{entry.summary}\n\n"
      io << entry.detail << "\n\n"
      io << "Run `apropos #{entry.name} --help` for exact flags.\n"
    end
  end
end
