require "yaml"
require "./conventions"

module Apropos
  # Skill wrapper generation: for every `skill: true` doc, emit a
  # `.claude/skills/<slug>/SKILL.md` whose frontmatter carries the doc's `name`
  # (its slug) and `description` verbatim, and whose body is a generated banner
  # plus a pointer back to the source doc. The wrappers are the one *committed*
  # generated artifact, so their bytes must be stable — the `--check`
  # gate byte-compares them.
  module Skills
    extend self

    # Raised on a slug collision (two skill docs sharing a filename) or a skill
    # doc missing its required `description`. `generate` fails closed on these.
    class Error < Apropos::Error
    end

    BANNER = "<!-- GENERATED by `apropos generate` — do not edit. Edit the source doc instead. -->"

    # The desired wrapper file bodies, keyed by slug, for every skill doc in
    # `conventions`. Deterministic and idempotent. Raises on a collision or a
    # missing description.
    def wrappers(conventions : Array(Convention)) : Hash(String, String)
      sources = {} of String => String
      result = {} of String => String
      conventions.each do |convention|
        next unless convention.skill?
        slug = slug_for(convention.path)
        if existing = sources[slug]?
          raise Error.new(
            "skill slug collision on '#{slug}': #{existing} and #{convention.path}")
        end
        sources[slug] = convention.path
        result[slug] = render(convention, slug)
      end
      result
    end

    # The slug for a doc: its filename without the `.md` extension. Windows-aware
    # via `Path` rather than a hardcoded separator.
    def slug_for(path : String) : String
      Path[path].basename(".md")
    end

    private def render(convention : Convention, slug : String) : String
      description = convention.frontmatter.description
      if description.nil?
        raise Error.new("skill doc #{convention.path} has `skill: true` but no `description`")
      end

      String.build do |io|
        io << YAML.dump({"name" => slug, "description" => description})
        io << "---\n\n"
        io << BANNER << "\n\n"
        io << "Read `" << convention.path << "` and follow it.\n"
      end
    end
  end
end
