#!/usr/bin/env bash
# Run the spec suite under kcov and enforce a line-coverage gate.
#
# Plain kcov has no built-in threshold flag, so this script reads the
# percentage back from kcov's coverage.json and fails below the threshold.
#
# The thin binary entry point (src/agent_apropos.cr) is excluded from the line count:
# it is a single delegating line, driven end-to-end by the integration specs as
# a subprocess (which kcov cannot instrument), so counting it would be
# misleading. This is the one documented, reviewed exclusion.
set -euo pipefail

THRESHOLD="${COVERAGE_THRESHOLD:-100}"
OUT_DIR="coverage"
SPEC_BIN="bin/coverage_specs"
ENTRY="spec/coverage_entry.cr"

command -v kcov >/dev/null 2>&1 || { echo "error: kcov not found on PATH"; exit 1; }
command -v jq >/dev/null 2>&1 || { echo "error: jq not found on PATH"; exit 1; }

# Build a single spec binary that requires every *_spec.cr, so kcov has one
# executable to instrument. Generated, then removed on exit.
cleanup() { rm -f "$ENTRY"; }
trap cleanup EXIT
{
  echo '# GENERATED by scripts/coverage.sh — safe to delete.'
  find spec -name '*_spec.cr' | sort | sed -E 's#^spec/#require "./#; s#$#"#'
} > "$ENTRY"

mkdir -p bin
rm -rf "$OUT_DIR"
crystal build "$ENTRY" -o "$SPEC_BIN" --debug

kcov \
  --include-path="$(pwd)/src" \
  --exclude-pattern="src/agent_apropos.cr" \
  "$OUT_DIR" "$SPEC_BIN"

# kcov writes a per-binary coverage.json; find it and read percent_covered.
JSON="$(find "$OUT_DIR" -name coverage.json | head -n1)"
[ -n "$JSON" ] || { echo "error: kcov produced no coverage.json"; exit 1; }

PERCENT="$(jq -r '.percent_covered' "$JSON")"
[ -n "$PERCENT" ] && [ "$PERCENT" != "null" ] || { echo "error: no percent_covered in $JSON"; exit 1; }

echo "Line coverage: ${PERCENT}% (threshold ${THRESHOLD}%)"
# Compare as floats; fail below threshold.
awk -v c="$PERCENT" -v t="$THRESHOLD" 'BEGIN { exit (c + 0 >= t + 0) ? 0 : 1 }'
